[package]
name = "Rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
h2 = "0.3.20"
bytes = "1"
#http = "0.2"
tokio = { version = "1.29", features = ["full"] }
hyper = "1.0.0-rc.4"
rocket = "0.5.0-rc.3"
syn = "2.0"
diesel = "2.1"
code_gen = { path = "code_gen" }
test_http = { path = "test_http" }
test_lib = { path = "test_lib" }
my_macro = { path = "my_macro" }
