[package]
name = "contacts"
version = "0.1.0"
edition = "2024"

[dependencies]
erp = { path = "../../erp" }
code_gen = { path = "../../code_gen" }

[lib]
crate-type = ["dylib"]

[dev-dependencies]
base = { path = "../base" }
web = { path = "../web" }
mail = { path = "../mail" }
serde_json.workspace = true
