[package]
name = "code_gen"
version = "0.1.0"
authors = ["0ddlyoko"]
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = "2.0"
tokio = { version = "1", features = ["full"] }
test_lib = {path = "../old_test_lib" }
